export const STUDENT_SIGN_IN = "STUDENT_SIGN_IN";
export const TEACHER_SIGN_IN = "TEACHER_SIGN_IN";
export const ADMIN_SIGN_IN = "ADMIN_SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";

export const GET_TEACHERS_BY_CLASS_ID = "GET_TEACHER_BY_CLASS_ID";
export const GET_ALL_TEACHERS = "GET_ALL_TEACHERS";

export const GET_STUDENT_HOMEWORK_BY_TEACHERID =
  "GET_STUDENT_HOMEWORK_BY_TEACHERID";
export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";

export const UPLOAD_HOMEWORK = "UPLOAD_HOMEWORK";
export const GET_CLASS_BY_TEACHER_ID = "GET_CLASS_BY_TEACHER_ID";
export const GET_STUDENT_BY_CLASS_ID = "GET_STUDENT_BY_CLASS_ID";

export const GET_ALL_HOMEWORK = "GET_ALL_HOMEWORK";
